### ISSUE TITLE
if the private ntfy server name is long in the ios list of topics, it is hard to see topic name

### ISSUE THREAD

**Issue by aappddeevv** [binwiederhier/ntfy#567] opened 2023-01-01 16:41 UTC
If your server name is really long for a private instance, the servername+topic name is long enough that it is hard to see the topic clearly. Not sure what to do except perhaps have a toggle to remove server name or shorten server name in some clever fashion.

**Comment by binwiederhier** [comment] 2023-01-08 20:20
This is a duplicate of #357

**Closed by binwiederhier** 2023-01-08 20:20 UTC
