### ISSUE TITLE
Missing certificate bundle in Docker image

### ISSUE THREAD

**Issue by tfheen** [binwiederhier/ntfy#359] opened 2022-07-09 19:31 UTC
When publishing a notification to my server running the 1.27.2 Docker image, I get an error in the log: `Unable to publish poll request: Post "https://ntfy.sh/f9a14d6123f[…]": x509: certificate signed by unknown authority`. I think the CA bundle is missing.

**Comment by binwiederhier** [comment] 2022-10-01 20:11
My apologies for the delay, but #387 :-D 

I tried this and I cannot reproduce it:

```
ocker run \
  -p 2080:80 \
  -it \
  binwiederhier/ntfy \
    --debug \
    serve \
    --base-url http://127.0.0.1 \
    --upstream-base-url https://ntfy.sh

2022/10/01 20:10:21 INFO Listening on :80[http], ntfy 1.28.0, log level is DEBUG
2022/10/01 20:10:23 DEBUG 172.17.0.1 HTTP POST /mytopic Dispatching request
2022/10/01 20:10:23 DEBUG 172.17.0.1/mytopic/GVkLPnJ7eJoj Received message: event=poll_request, body=11 byte(s), delayed=false, firebase=true, cache=false, up=false, email=
2022/10/01 20:10:23 DEBUG 172.17.0.1/mytopic/GVkLPnJ7eJoj Publishing poll request to https://ntfy.sh/2aa077f08d5bb00f192c983fcefeb56ce7feee97059c1b0f2ed26dd916913aa5
2022/10/01 20:11:21 DEBUG Manager: Starting
2022/10/01 20:11:21 DEBUG Manager: Deleted 0 stale visitor(s)
2022/10/01 20:11:21 DEBUG Manager: Pruning messages older than 2022-10-01 08:11:21
2022/10/01 20:11:21 INFO Stats: 1 messages published, 0 in cache, 0 topic(s) active, 0 subscriber(s), 1 visitor(s), 0 mails received (0 successful, 0 failed), 0 mails sent (0 successful, 0 failed)
2022/10/01 20:11:21 DEBUG Manager: Finished
```

```
curl -d hi -H "X-Poll-ID: abc" localhost:2080/mytopic
{"id":"GVkLPnJ7eJoj","time":1664655023,"event":"poll_request","topic":"mytopic","message":"New message","poll_id":"abc"}
```

Maybe the newer Alpine image contains updated certs.

**Comment by binwiederhier** [comment] 2022-10-01 20:13
I'm going to close this for now, but I'm happy to re-open at any time.

**Closed by binwiederhier** 2022-10-01 20:13 UTC
Labels: 🪲 bug, server
