### ISSUE TITLE
NATS

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#78] opened 2022-01-01 12:54 UTC
Continuation of https://github.com/binwiederhier/ntfy/issues/19#issuecomment-1002769688

**Comment by gedw99** [comment] 2022-01-01 12:56
Just a discussion of it NATS is a good option for nfty.

**Comment by gc-ss** [comment] 2022-01-01 21:25
> The pure GRPC basis is definitely a nice option.

You got it!

Although you know this - just repeating to ensure we are all on the same page: due to GRPC, it's automatic to use ANY language as the pub-sub nodes.

For example, Tyler and his team focuses on Go, and we are a Python shop.

However, because of GRPC, we are easily able to use Python with LIftbridge.

> Does LIftbridge has the ability for the client to automatically connect to nearest server and then fail over to nearest etc ?

It does and more (it really does a good job of HA replication - something that's critical for prod workloads)

Just ask and confirm with them:

Tyler and his team is fantastic and has OSS the very product he is building his company on.

Just drop by on their Slack to ask any questions you have - no matter how basic 👍

**Comment by gedw99** [comment] 2022-01-02 00:34
Hey @gc-ss 

Are you using it in production ? 
What gotchas have you found in your usage ?

I ask because I tried it a while ago ( maybe 8 months ago ) and it had some issues. I think the Raft replication was a little buggy if I recall.

Also nats Jetstream is designed as a message hub with publishers and consumers of streams decoupled at compile time . So at runtime you can hook a consumer up to a publishers stream and subject . 
I don’t think ( but it’s been a while ) that Liftbridge supports this type of decoupled functionality. Not everyone needs that of course though.

**Comment by gc-ss** [comment] 2022-01-02 00:41
Yes, it's being used in production. The biggest gotchas have been due to us using Python while LIftbridge documentation often assumes a Go context. Since they don't seem to be a Python shop, they are not as interested in reproducing Python issues.

However, for core Liftbridge issues, I've obtained responses and fixes (when needed) within days without a commercial contract

>  a message hub with publishers and consumers of streams decoupled at compile time . So at runtime you can hook a consumer up to a publishers stream and subject

That's exactly the usecase I have for Liftbridge in production.

You might be interested in reading up why Liftbridge was designed even though nats Jetstream exists.

Feel free to drop by on their Slack to ask any questions you have - I use Liftbridge in a very niche way (strongly decoupled, multi environment (language/OS/onpremise/cloud) node data mesh) - they can answer these Liftbridge specific questions much better than I can 👍

**Comment by gc-ss** [comment] 2022-01-02 00:45
… and yes, your initial proposal to @binwiederhier that `ntfy` would be drastically simplified and scaled is correct using LiftBridge/NATS which is why I joined the conversation.

In this case, the publisher and consumer are the phone apps or webservice, as the case may be.

LiftBridge/NATS is the hosted message bus.

Very simple yet powerful cloud native (that can be hosted on a laptop if needed) architecture.

**Comment by gedw99** [comment] 2022-01-02 01:18
If your open to it would be nice to compare notes offline . I have never had an in-depth discussion about Liftbridge as I just used nats and before that Tibco rendezvous ( a commercial produce that does pretty much what nats Jetstream does ).

**Comment by gc-ss** [comment] 2022-01-02 01:23
> If your open to it would be nice to compare notes offline

Sure. If you have a calendly link, feel free to share. Otherwise I can put a temp. email here that you can email to

let me know

**Comment by gedw99** [comment] 2022-01-02 01:39
I have a telegram link on my GitHub profile ..  do you use telegram ?



I am in Berlin, Germany btw, so gmt +1

**Comment by gc-ss** [comment] 2022-01-02 01:41
> do you use telegram

I dont. If you don't mind sending me a quick email to:

`chatwithgedw99@ssgc.anonaddy.com`

I will get back to you and we can setup a meeting from there :)

**Comment by gedw99** [comment] 2022-01-02 01:43
I am reading up on the latest release . It seems to have most of the architectural features now.

I use GRPC heaps and so it’s interesting to use Liftbridge since it’s just more GRPC.

I was looking for security stuff like NATS Jetstream had so that streams can be restricted by user / roles. It looks like with Liftbridge you have to do this yourself

**Comment by gc-ss** [comment] 2022-01-02 01:46
> I was looking for security stuff like NATS Jetstream had so that streams can be restricted by user / roles. It looks like with Liftbridge you have to do this yourself

Sure, since I already use `oso` or `opa` for Authz, I prefer using those for this as well instead of yet another different thing NATS Jetstream offers.

I am interested to know how you find the latest Liftbridge

**Comment by gedw99** [comment] 2022-01-02 01:52
I know OPA. OSO  is new one to me…

**Comment by binwiederhier** [comment] 2022-02-05 14:45
I was gonna just close this ticket, but I do think I owe you guys the courtesy of fully understanding what you'd want to use NATS for in ntfy.

I think I understand what it is (a pub sub system), and I think I understand what you'd want me to do (replace the guts of ntfy with NATS), but what I don't understand is _why_? What's the use case you see or want to support that needs NATS. Why would I do weeks of work to implement NATS? It feels like a pointless refactor at this point. I'd add complexity for features I don't want to need, no?

**Comment by gedw99** [comment] 2022-02-05 14:50
@binwiederhier 

I can really see your point !!

At the moment i love the fact that you have SSE, WS, CURL, etc ways of interacting with the system.  its really a PITA to do that with NATS but you have already done it.

If you put NATS behind everything and ONLY used it for the Federation aspects it would be useful ? Maybe.. It used RAFT under the hood to do its HA, Clustering.   

Happy to explore this with you if you want...

**Comment by gc-ss** [comment] 2022-02-07 20:55
> but what I don't understand is why? What's the use case you see or want to support that needs NATS. Why would I do weeks of work to implement NATS? It feels like a pointless refactor at this point. I'd add complexity for features I don't want to need, no?

This is a very strategic question, the answer to which is a long scenarios and requirements spec.

Before writing that out, let me share my usecase for `ntfy`.

`ntfy` to me is a prototype event sharing producer-consumer system.

The current `ntfy` prototype has proven to us that:

1. There's a huge demand for such an event sharing producer-consumer system - i.e., you have addressed the Market risk (people are interested in this as it solves a problem they have).
2. There's proof that such an event sharing producer-consumer system can be built - i.e., you have addressed the Product risk (you have the ability to build a product that solves the problem)

The next steps are to build out the product more and there's one big gaping hole in the current `ntfy` prototype: Reliability.

Reliability has to be the cornerstone of an event sharing producer-consumer system.

As people build out and start depending on `ntfy` for their event sharing needs, reliability will start to rear its ugly head.

Some things/reports we will see based off my experience in event sharing producer-consumer systems:

i. Messages sent weren't received by all consumers
ii. Duplicate messages were received by consumers
iii. Messages were thought to be sent weren't received by any consumers
iv. A temporary spike in events from certain producers overwhelmed the single `ntfy` service and made it crash, losing state/events and there's no ability to "scale out" the system
v. Certain popular topics that are important, but fire only occasionally, have an overwhelming number of consumers and the resource overhead of idle connections are "too much" for one server (it would be awesome to pause/resume these topics on demand to efficiently utilize compute resources)

These will show up as `ntfy` becomes popular.

These are all usecases well solved by LiftBridge/NATS and we haven't even discussed HA needs yet as @gedw99 has pointed out some scenarios (which I would classify as the second phase of reliability).

**Comment by gedw99** [comment] 2022-02-08 08:43
here is a good video demo by the main Lead developer of NATS showing how it does real time failover.
https://nats.io/blog/kv-cli/

NATS or LIftbridge give similar things BTW for Nfty. Nats and Liftbridge do have differences though.
I am going to answer the follow queries presuming your using NATS.

Yes its a 2nd phase thing !!  

yes most of those things you mentioned are fixed by NATS and LiftBridge:

i. Messages sent weren't received by all consumers
- Yep this is solved by both.

ii. Duplicate messages were received by consumers
- They are both at least once.

iii. Messages were thought to be sent weren't received by any consumers
- They both support ACK ( acknowledgement ) from the client if you use it.

iv. A temporary spike in events from certain producers overwhelmed the single ntfy service and made it crash, losing state/events and there's no ability to "scale out" the system
- They both support runs as a cluster. 
- Nats does automatic load balancing an can do it just over http ( if you want ). This video really shows the off the geo load balancing: https://www.youtube.com/watch?v=qZ7fww7_s7A. In this case its using Caddy http roundtripper to do it: https://github.com/ripienaar/nats-roundtripper


v. Certain popular topics that are important, but fire only occasionally, have an overwhelming number of consumers and the resource overhead of idle connections are "too much" for one server (it would be awesome to pause/resume these topics on demand to efficiently utilize compute resources)
- You can tag topics to have priority.  Via the nats cli you can test this out.
- You can also split the traffic.
- Also you can orchestrate upgades of NATS. Say you had 3 nats clusters in EU, and also a cluster in US and Asia. If you wanted to upgrade them all you can take each cluster offline, and the clients will failover automatically to the nearest other cluster with no disruption to the client.  Then you upgrade it, and then do the same for the other 2 clusters.
I can supply some scripts that do this for you. It just uses the NATS CLI to do it.

Security is built into NATS too. You can create users and roles and they propagate to all the clusters.

I hope this answers all these questions ???

**Closed** 2022-02-11 14:31 UTC
Labels: enhancement, question, server

**Comment by gedw99** [comment] 2022-02-11 15:41
Yep I do . It’s for the bet
