### ISSUE TITLE
v6 support

### ISSUE THREAD

**Issue by deavmi** [binwiederhier/ntfy#547] opened 2022-12-16 21:08 UTC
Could you please add a v6 address to the vanilla server and an AAAA record. I only have v6 where I live and it would help me use this app (I use it a lot)

**Comment by binwiederhier** [comment] 2022-12-17 02:14
Closing this is as a duplicate of #519. Please feel free to read this comment (https://github.com/binwiederhier/ntfy/issues/519#issuecomment-1328145216).

**Closed by binwiederhier** 2022-12-17 02:14 UTC
