### ISSUE TITLE
IOS PWA (staging): crash on clicking OS notification

### ISSUE THREAD

**Issue by gedw99** [binwiederhier/ntfy#798] opened 2023-06-29 16:38 UTC
https://staging.ntfy.sh/app 

IOS Safari PWA

I think this is already an issue but just in case :)

```sh
UnknownError: Attempt to get count from database without an in-progress transaction
 UnknownError: Attempt to get count from database without an in-progress transaction
  at undefined (UnknownError: Attempt to get count from database without an in-progress transaction:undefined:undefined)
  at undefined ( UnknownError: Attempt to get count from database without an in-progress transaction:undefined:undefined)
  at timeout (https://staging.ntfy.sh/static/media/index-b3b2409b.js:62485:222)
  at t (https://staging.ntfy.sh/static/media/index-b3b2409b.js:4036:221)
  at Vh ([native code]:undefined:undefined)
  at timeout (https://staging.ntfy.sh/static/media/index-b3b2409b.js:24470:222)
  at t (https://staging.ntfy.sh/static/media/index-b3b2409b.js:5832:221)

UnknownError: Attempt to get count from database without an in-progress transaction
 UnknownError: Attempt to get count from database without an in-progress transaction
  at Rq@https://staging.ntfy.sh/static/media/index-b3b2409b.js:336:71367
  at x8@https://staging.ntfy.sh/static/media/index-b3b2409b.js:240:3960
  at O8@https://staging.ntfy.sh/static/media/index-b3b2409b.js:240:6876
  at QH@https://staging.ntfy.sh/static/media/index-b3b2409b.js:317:5812
  at withI18nextTranslation(QH)@https://staging.ntfy.sh/static/media/index-b3b2409b.js:268:3139
  at i$@https://staging.ntfy.sh/static/media/index-b3b2409b.js:61:18625
  at s$@https://staging.ntfy.sh/static/media/index-b3b2409b.js:61:19028
  at Q$@https://staging.ntfy.sh/static/media/index-b3b2409b.js:61:29591
  at A8@https://staging.ntfy.sh/static/media/index-b3b2409b.js:240:6337
  at M8@https://staging.ntfy.sh/static/media/index-b3b2409b.js:249:781
  at Suspense
  at Aq@https://staging.ntfy.sh/static/media/index-b3b2409b.js:336:70571
```

**Comment by gedw99** [comment] 2023-06-29 16:42
PWA on Chrome on Mac Book was slow getting messages - About  2 to 5 minutes. I was testing between IOS and MacBook

**Comment by nimbleghost** [comment] 2023-06-29 16:51
Thanks for the repot. This is a duplicate of #787

**Closed** 2023-06-30 01:26 UTC
Labels: 🪲 bug
