### ISSUE TITLE
Text color Android (enhancement)

### ISSUE THREAD

**Issue by osering** [binwiederhier/ntfy#558] opened 2022-12-25 01:27 UTC
Great app, but unfortunately not possible to change text color (it's just plain white).
Suggest: some markdown or other tools, to change color of any character/word in message & title text

**Comment by binwiederhier** [comment] 2022-12-25 01:28
Hi @osering, thanks for the suggestion. This is a duplicate of #310. 
You may :+1: the other ticket's first comment to indicate that you'd also like this feature.

**Closed by binwiederhier** 2022-12-25 01:28 UTC
