### ISSUE TITLE
crash because language tag

### ISSUE THREAD

**Issue by alexyutmp** [binwiederhier/ntfy#951] opened 2023-11-19 01:46 UTC
:lady_beetle: **Describe the bug**

- Create a docker image in synology docker
- Login to ntfy
- Change language to Simplified Chinese
- Do a push test inside ntfy,
- It crashes and shows the error messages

> RangeError: invalid language tag: zh_Hans

Full stack is attached.

:computer: **Components impacted**

:bulb: **Screenshots and/or logs**
RangeError: invalid language tag: zh_Hans
  at DateTimeFormat ([native code]:undefined:undefined)
  at log (http://192.168.50.2:3680/static/media/index-9e24212a.js:343:286)
  at lse (http://192.168.50.2:3680/static/media/index-9e24212a.js:283:326)
  at isMounted (http://192.168.50.2:3680/static/media/index-9e24212a.js:19519:38)
  at callback (http://192.168.50.2:3680/static/media/index-9e24212a.js:44029:40)
  at callback (http://192.168.50.2:3680/static/media/index-9e24212a.js:39765:40)
  at callback (http://192.168.50.2:3680/static/media/index-9e24212a.js:39693:40)
  at callback (http://192.168.50.2:3680/static/media/index-9e24212a.js:39547:40)
  at callback (http://192.168.50.2:3680/static/media/index-9e24212a.js:35915:40)
  at callback (http://192.168.50.2:3680/static/media/index-9e24212a.js:34866:40)
  at unstable_now (http://192.168.50.2:3680/static/media/index-9e24212a.js:1560:25)
  at unstable_now (http://192.168.50.2:3680/static/media/index-9e24212a.js:1927:25)
RangeError: invalid language tag: zh_Hans
  at use@http://192.168.50.2:3680/static/media/index-9e24212a.js:326:240
  at div
  at @http://192.168.50.2:3680/static/media/index-9e24212a.js:55:6195
  at @http://192.168.50.2:3680/static/media/index-9e24212a.js:61:22351
  at div
  at @http://192.168.50.2:3680/static/media/index-9e24212a.js:55:6195
  at @http://192.168.50.2:3680/static/media/index-9e24212a.js:61:20670
  at div
  at div
  at t@http://192.168.50.2:3680/static/media/index-9e24212a.js:263:1468
  at IR@http://192.168.50.2:3680/static/media/index-9e24212a.js:286:86950
  at ise@http://192.168.50.2:3680/static/media/index-9e24212a.js:286:86534
  at rse@http://192.168.50.2:3680/static/media/index-9e24212a.js:286:86335
  at oK@http://192.168.50.2:3680/static/media/index-9e24212a.js:240:3960
  at pK@http://192.168.50.2:3680/static/media/index-9e24212a.js:240:6225
  at main
  at @http://192.168.50.2:3680/static/media/index-9e24212a.js:55:6195
  at @http://192.168.50.2:3680/static/media/index-9e24212a.js:61:13100
  at Rde@http://192.168.50.2:3680/static/media/index-9e24212a.js:409:15093
  at div
  at @http://192.168.50.2:3680/static/media/index-9e24212a.js:55:6195
  at @http://192.168.50.2:3680/static/media/index-9e24212a.js:61:13100
  at Ode@http://192.168.50.2:3680/static/media/index-9e24212a.js:409:13970
  at oK@http://192.168.50.2:3680/static/media/index-9e24212a.js:240:3960
  at gK@http://192.168.50.2:3680/static/media/index-9e24212a.js:240:6876
  at Cce@http://192.168.50.2:3680/static/media/index-9e24212a.js:372:5839
  at withI18nextTranslation(Cce)@http://192.168.50.2:3680/static/media/index-9e24212a.js:250:3139
  at GN@http://192.168.50.2:3680/static/media/index-9e24212a.js:61:18738
  at YN@http://192.168.50.2:3680/static/media/index-9e24212a.js:61:19141
  at D3@http://192.168.50.2:3680/static/media/index-9e24212a.js:61:29735
  at fK@http://192.168.50.2:3680/static/media/index-9e24212a.js:240:6337
  at _K@http://192.168.50.2:3680/static/media/index-9e24212a.js:249:781
  at Pde@http://192.168.50.2:3680/static/media/index-9e24212a.js:409:12649
  at Suspense
  at Ade@http://192.168.50.2:3680/static/media/index-9e24212a.js:409:12874

:crystal_ball: **Additional context**

**Comment by binwiederhier** [comment] 2023-11-19 01:51
Thank you for reporting. 
This is a duplicate of #852, fixed in #922. 

Will be in the next release which will be out (hopefully) soon

**Closed by binwiederhier** 2023-11-19 01:51 UTC
Labels: 🪲 bug
