### ISSUE TITLE
Client user/notification group

### ISSUE THREAD

**Issue by etfz** [binwiederhier/ntfy#515] opened 2022-11-21 12:01 UTC
Hi,

Would love to try this project out, but the main concern for me is, if I understand correctly, that there are no user accounts involved, and each client is configured on a subscription basis, meaning dealing with multiple client devices (PC, phone) quickly becomes very cumbersome.

What about a feature to create notification groups or something? A URL that you would subscribe to, which would receive notifications from multiple subscriptions. Maybe it requires client user accounts to make sense.

Or if there are other ways I can avoid the need to manually synchronise my subscriptions between devices.

**Comment by binwiederhier** [comment] 2022-11-24 11:34
Thank you for reporting this. And my apologies it took so long to respond. I believe this is a duplicate of #159 and one of the highest requested features. Please leave a :+1: on the top comment to prioritize the feature.

**Closed by binwiederhier** 2022-11-24 11:34 UTC
