### ISSUE TITLE
Unable to use auth on new install

### ISSUE THREAD

**Issue by sebastien4** [binwiederhier/ntfy#421] opened 2022-09-30 16:53 UTC
Hi,

I'm trying to make auth work on fresh Ubuntu install, using this:

- ntfy systemctl service, using _ntfy serve --config /path/server.yml_
- in _server.xml_, absolute path to _auth-file_ and _auth-default-access: "deny-all"_

I'm following this: https://ntfy.sh/docs/config/#example-private-instance
When I try to add new user, I get this: _option auth-file not set; auth is unconfigured for this server_

What am I doing wrong? Sorry if I miss sth usually clear :/

Thanks.

**Comment by binwiederhier** [comment] 2022-09-30 21:15
Likely a duplicate of https://github.com/binwiederhier/ntfy/issues/401#issuecomment-1260287006

This is a documentation failure. The systemd service runs as user `ntfy`, so you have to execute the ACL updates as that user.

**Comment by sebastien4** [comment] 2022-10-01 14:21
Indeed, you must use paths (bin, etc, db) mentioned in documentation in order for this to work.
Thanks @binwiederhier.

**Closed** 2022-10-01 18:55 UTC
