### ISSUE TITLE
Emergency Priority on Android

### ISSUE THREAD

**Issue by danmed** [binwiederhier/ntfy#417] opened 2022-09-29 22:21 UTC
I've been trying out ntfy and it's.. well it's awesome.. so much quicker than pushover..

The problem i have is that i want to use it for my alarm notifications but i cannot figure out how to set it as an emergency alert on android.

My phone is almost always on vibrate only and after 11pm it's in DND.

I've figured out how to ignore DND.. but how can i get it to ignore vibrate and play a sound (loud!) 

With pushover I set the priority to 2.. but i can't find the equivalent with ntfy

**Comment by binwiederhier** [comment] 2022-09-30 01:32
I found this is a great sound for max priority: https://cdn.freesound.org/previews/607/607878_12946258-lq.mp3

**Comment by danmed** [comment] 2022-09-30 08:31
> > I've figured out how to ignore DND.. but how can i get it to ignore vibrate and play a sound (loud!)
> 
> I just tried and if I
> 
> * set my phone to "Ring" (my OnePlus phone has a slider on the side of the phone)
> * enable DND
> * And set the "max priority" channel to "override DND"
> 
> It will play a sound even with DND.
> 
> Here's what that looks like. You can even set a custom ringtone for max priority items: ![image](https://user-images.githubusercontent.com/664597/193169569-eafe35c8-8792-4a06-b8e0-c53c0affab4b.png)

Hi,

thank you for your reply, but i don't want to take my phone off silent... (for a few reasons).. I was just wondering if NTFY could by pass the "silent" mode like pushover can.

**Comment by binwiederhier** [comment] 2022-09-30 15:59
> but i don't want to take my phone off silent... 

Doesn't DND override all sounds and mutes them?

> I was just wondering if NTFY could by pass the "silent" mode like pushover can.

I thought I had looked into that and decided it wasn't possible. But if Pushover does it, it must be possible ... It's a valid request.

**Comment by danmed** [comment] 2022-09-30 21:28
> > but i don't want to take my phone off silent...
> 
> Doesn't DND override all sounds and mutes them?
> 
> > I was just wondering if NTFY could by pass the "silent" mode like pushover can.
> 
> I thought I had looked into that and decided it wasn't possible. But if Pushover does it, it must be possible ... It's a valid request.

Thank you for considering it.. here is the Pushover info : https://pushover.net/api#priority

**Comment by danmed** [comment] 2022-11-13 00:36
I had to set up pushover on my phone again (new phone) and by default it wasn't bypassing my DND.. it turns out i'd had to alter some settings in the client and the main one is to play high priority alerts as an alarm which bypasses DND by default.. maybe that will assist in progressing this one! (it also allows customising the sound played for high priority alerts)

**Comment by binwiederhier** [comment] 2022-11-13 11:38
> had to alter some settings in the client

If you could share the steps or screenshots that'd be helpful :-D

**Comment by danmed** [comment] 2022-11-14 03:58
![Screenshot_20221114-035739](https://user-images.githubusercontent.com/3878490/201572305-decb1779-d5c8-4f90-9a70-03249055befb.png)

**Comment by binwiederhier** [comment] 2022-11-17 14:44
What app is that from? Is that from Android, or in Pushover? It'd be more helpful if you could provide specific steps in Android. If it's a pushover setting, then don't bother, because I won't know what Pushover does under the hood.

**Comment by danmed** [comment] 2022-11-17 16:59
It's Pushover.. i just figured that the description of what it does might
help

**Comment by binwiederhier** [comment] 2022-11-28 02:16
I have managed to produce a looping alarm sound, even with DND enabled, and even when the phone is silent. I think I can make a similar toggle to the screenshot above. Working on this now.

**Comment by danmed** [comment] 2022-11-28 16:18
> I have managed to produce a looping alarm sound, even with DND enabled, and even when the phone is silent. I think I can make a similar toggle to the screenshot above. Working on this now.

Awesome!

**Comment by binwiederhier** [comment] 2022-11-29 20:22
Alright I got something that reliably works. It is a little odd that it's not possible to configure the sound for this (yet), so I have to pick a sound. For my phone, the default notification sound (on repeat) works the best, but I don't know if that's ok with other phones.

I'm going to implement it this way and later, maybe if I ever get to #6, we can make this configurable.

**Comment by danmed** [comment] 2022-11-29 20:24
Happy to give it a test.. I'm using a pixel 6a

**Comment by binwiederhier** [comment] 2022-11-29 20:25
Well, right now there is no toggle and the notification sound will literally not stop looping until you kill the app. So I'll let you know when I have something that is actually close to ready.

**Comment by binwiederhier** [comment] 2022-11-30 03:50
Here's an .apk you can try: https://drive.google.com/file/d/11ZbKDPz4fz9RvvtAi1W3ylATr_L5AlOG/view?usp=share_link

(Be sure to back up your config using Settings -> Backup)

**Comment by binwiederhier** [comment] 2022-11-30 19:35
@danmed Let me know if it generally works for you.

There has been a discussion on Discord/Matrix about this feature, and about whether or not to add a new priority level or a new flag to trigger this insistent behavior. Here are the options

1. Add client-side toggle turn the normal "priority 5" behavior into the looping sound. No server side changes.
2. Add new priority `Priority: 6` (aka `Priority: emergency`), which will by default trigger the looping sound. There would be a cllient-side toggle to switch this behavior off. This is a little weird, because now the max priority is not the highest anymore. This requires server side changes, and may be a slightly breaking change for clients.
3. Add `Insistent: yes` header, which will by default trigger the looping sound. There would be a client-side toggle to ignore this flag. This is a little off for something like `Priority: min; Insistent: yes`, because that would not alert at all. This requires server side changes. 

Arguably, option 1+2 are kind of the same, because they both have a client-side toggle to turn the behavior off/on. 

Thoughts?

**Comment by danmed** [comment] 2022-12-04 22:40
Hey, really sorry.. it's been a hectic weekend.. ill try and test the APK
in the next couple of days..

as for the options for implementation.. it makes sense to me to have a new
priority for it but i do understand the breaking changes this could cause..

**Comment by binwiederhier** [comment] 2022-12-05 01:17
No worries. 

I have pretty much decided to either no release this feature at all, or just the same way that you suggested, with a new option that redefines priority 5 (option 1). 

The problem is that I have not had much success getting people to try it. So far two people have tried. It worked for one, and not the other. So rather than releasing a brittle feature that no-one wants, I'd rather not release it at all. 

Maybe I can get some more people to test once I have a few more features bundled into an RC.

![image](https://user-images.githubusercontent.com/664597/205528632-e8bb7825-86e7-4551-af9c-523e055fb430.png)

**Comment by binwiederhier** [comment] 2022-12-05 01:27
Current score:

- Works: @binwiederhier on OnePlus 8 (Android 12) + Emulator (Android 12) + Emulator (Android 13), @cmeis (Android 12)
- Doesn't work: @nwithan8 (Android 13)

**Comment by wunter8** [comment] 2022-12-06 13:46
Works: @wunter8 on Pixel 5 (Android 13)

**Comment by binwiederhier** [comment] 2023-03-13 01:05
I forgot to close this ticket. This was merged and released some time ago.

**Closed by binwiederhier** 2023-03-13 01:05 UTC
Labels: enhancement, android-app, in-progress 🏃

**Comment by jvandenbroek** [comment] 2023-10-24 08:59
Unfortunately this feature doesn't seem to work on my Poco F3 with MIUI 13. Log gives the following traceback:
```
1698136715441 2023-10-24 10:38:35.441 D NtfyNotifService Media player: Playing insistent alarm on alarm channel
1698136715446 2023-10-24 10:38:35.446 W NtfyNotifService Media player: Failed to play insistent alarm
Exception:
java.io.IOException: setDataSource failed.: status=0x80000000
        at android.media.MediaPlayer.nativeSetDataSource(Native Method)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1210)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1197)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1108)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1028)
        at io.heckel.ntfy.msg.NotificationService.maybePlayInsistentSound(NotificationService.kt:453)
        at io.heckel.ntfy.msg.NotificationService.displayInternal(NotificationService.kt:115)
        at io.heckel.ntfy.msg.NotificationService.displayInternal$default(NotificationService.kt:90)
        at io.heckel.ntfy.msg.NotificationService.display(NotificationService.kt:32)
        at io.heckel.ntfy.msg.NotificationDispatcher.dispatch(NotificationDispatcher.kt:35)
        at io.heckel.ntfy.service.SubscriberService$onNotificationReceived$1.invokeSuspend(SubscriberService.kt:264)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
There is no option to make DND exemptions per notification on this ROM as shown by OP, really annoying and I will probably avoid MIUI in the future. However for some reason it does work even without this setting on the Home Assistant app by setting the channel to alarm_stream: https://companion.home-assistant.io/docs/notifications/critical-notifications/#android-alarm-stream

So if the same logic could be implemented in ntfy, I (and probably others) would be very happy :-) Thanks for the great work!

**Comment by juanrgm** [comment] 2023-11-30 10:03
Customizing the number of intervals and delay between sounds would be great.

In the meantime I had to add a delay to the end of the audio track with ffmpeg.

**Comment by gwlg-mjh** [comment] 2024-03-07 16:46
Thanks, I was looking for a way to be able to override the silent mode so I can do a find my phone feature with Alexa and Home Assistant and not have to boot up a pc or laptop and do the Google/Samsung version.  The only thing I would say is that when I originally saw this option in the settings it wasn't obvious that it would override the silent/vibrate setting on the phone.
