### ISSUE TITLE
Android: UnifiedPush subscription not using saved user credentials

### ISSUE THREAD

**Issue by ryester19** [binwiederhier/ntfy#382] opened 2022-08-17 12:53 UTC
Using Ntfy server 1.27.2, Android Ntfy app 1.13.0, and Android Element 1.4.32
ACL is enabled on the server, and auth-default-access set to 'deny-all'

The subscription that Element sets up for UnifiedPush use does not use the saved user credentials in the ntfy app. The user is an admin, and the "Managed users" page does say the user is being used for this topic. The only error I see in the server log is a "unauthorized: unauthorized" message

In order to get Element to pass the "Test Push" test, I have to give anonymous read-write access to the topic that's created by Element

Android log:
https://nopaste.net/PFREHjyS0Q

**Comment by MaximilianGaedig** [comment] 2022-08-18 09:40
Just ran into the same issue, the workaround for now is using the ntfy.sh server for unified push and your own for other things but that's no real workaround as you are not using your server

**Comment by binwiederhier** [comment] 2022-08-18 15:55
This is not a bug in ntfy, but rather a design limitation of UnifiedPush (UP). In UP, the URL is the secret, user/password cannot be used in the spec. 

This explains this in more detail: https://unifiedpush.org/users/distributors/ntfy/#limit-access-to-some-users

Specifically this section:

> Pushers still need to be able to write to UnifiedPush topics to send push notifications. Add a rule to make UnifiedPush topics (they all start with “up”) world-writeable: `ntfy access '*' 'up*' write-only`

**Comment by binwiederhier** [comment] 2022-08-18 15:56
For more questions about UP, please check out the UP Matrix room(s)

**Comment by ryester19** [comment] 2022-08-18 18:51
Gotcha. To get around this limitation in a more user-friendly way, could we add a ACL sub-option in the config file or a toggle in the 'ntfy access' command?

**Comment by binwiederhier** [comment] 2022-08-29 14:45
@ryester19 Any suggestions?

**Comment by binwiederhier** [comment] 2022-09-03 18:31
Let me know if you have any suggestions. For now I'll close this issue.

**Closed by binwiederhier** 2022-09-03 18:31 UTC
Labels: android-app, question
